# Production Environment Site Attributes Configuration
# Overrides for production environment

# Production-specific configuration
default:
  # Production site information (will be merged with base config)
  description: "Production Manufacturing Facility"
  site_manager: "Production Manager"
  contact_email: "production@company.com"
  contact_phone: "+1-555-PROD-MGR"

  # Production environment specific
  environment: "production"
  debug_mode: false
  test_data: false
  high_availability: true

  # Full certification for production
  certification: ["ISO 9001", "ISO 14001", "ISO 45001", "ISO 50001"]
  operating_hours: "24/7"

  # Production infrastructure
  total_buildings: null               # Calculated from scenario
  total_area_sqm: null               # Calculated from scenario
  parking_spaces: 500
  has_security: true
  monitored_24x7: true

  # Production compliance
  audit_logging: true
  data_encryption: true
  backup_enabled: true
  disaster_recovery: true

# Production environment overrides
environment_overrides:
  production:
    debug_enabled: false
    mock_gps: false
    accelerated_time: false
    auto_cleanup: false
    log_level: "WARN"
    data_retention_days: 2555        # 7 years
    compliance_mode: "strict"

  critical:
    debug_enabled: false
    mock_gps: false
    accelerated_time: false
    auto_cleanup: false
    log_level: "ERROR"
    data_retention_days: 3650        # 10 years
    compliance_mode: "military"

# Production-specific sites
predefined_sites:
  hanoi_manufacturing:
    address: "Hanoi Industrial Park, Vietnam"
    latitude: 21.0285
    longitude: 105.8542
    description: "Primary manufacturing facility"
    timezone: "Asia/Ho_Chi_Minh"
    compliance_region: "APAC"

  hcmc_logistics:
    address: "HCMC Logistics Center, Vietnam"
    latitude: 10.7769
    longitude: 106.7009
    description: "Logistics and distribution center"
    timezone: "Asia/Ho_Chi_Minh"
    compliance_region: "APAC"

  singapore_hq:
    address: "Singapore Corporate Headquarters"
    latitude: 1.3521
    longitude: 103.8198
    description: "Corporate headquarters"
    timezone: "Asia/Singapore"
    compliance_region: "APAC"

# Production security and compliance
security_config:
  physical_security:
    access_control: "Biometric + Card"
    surveillance: "24/7 CCTV"
    security_personnel: true
    visitor_management: true

  cyber_security:
    network_segmentation: true
    firewall_configured: true
    intrusion_detection: true
    security_monitoring: true

  data_protection:
    gdpr_compliant: true
    data_classification: "Confidential"
    access_logging: true
  encryption_at_rest: true

# Production monitoring
monitoring_config:
  performance_monitoring: true
  uptime_monitoring: true
  capacity_monitoring: true
  security_monitoring: true

  alerting:
    email_alerts: true
    sms_alerts: true
    slack_integration: true
    escalation_policy: true